theme: jekyll-theme-cayman
title: [How do people search differenly? ]
description: [From different device, place, and region]
colors:
    gradient_left: "#c2185b"
    gradient_right: "#4a148c"
    header: "#fff"
    android_theme: "#4a148c"
    link: "#4a148c"
    section_title: "#c2185b" 